[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cngn = "4yR7dASbCgn1KPLsbJHXdpFMSP1bZUdXMGXdC5P7B4ud"

[programs.devnet]
cngn = "4yR7dASbCgn1KPLsbJHXdpFMSP1bZUdXMGXdC5P7B4ud"

[programs.mainnet]
cngn = "4yR7dASbCgn1KPLsbJHXdpFMSP1bZUdXMGXdC5P7B4ud"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/burn.ts"
